[build]
  command = "npm run build"
  publish = "dist"
  functions = "src/pages/api" # Apuntamos directamente a tu carpeta API

[context.production.environment]
  NODE_VERSION = "18"
  RESEND_API_KEY = "@resend_api_key"